# Usa una imagen base oficial de Python
FROM python:3.9-slim

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos de requisitos primero para aprovechar la caché de Docker
COPY alas_dataflow_1/requirements.txt .

# Instala las dependencias de Python
RUN pip install --no-cache-dir -r requirements.txt

COPY alas_dataflow_1/src ./src
COPY alas_dataflow_1/tests ./tests

# Comando para ejecutar tu aplicación
CMD ["python", "src/1_run_main_table_pipeline.py"]
