# Python image to use.
FROM python:3.12-alpine

# Set the working directory to /app
WORKDIR /app

# copy the requirements file used for dependencies
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Copy the rest of the working directory contents into the container at /app
COPY . .

# Run app.py when the container launches(para PRD no se usa ENTRYPOINT sino Gunicorn)
#ENTRYPOINT ["python", "app.py"]

# Use Gunicorn to run the app. Adjust the number of workers as needed.
# The syntax :$PORT tells Gunicorn to bind to the PORT environment variable.
CMD gunicorn -b :$PORT app:app --workers 3 --timeout 3600

